scp *.cpp rikhardur19@skel.ru.is:~/cpp/PA4/
scp Classes/*.cpp rikhardur19@skel.ru.is:~/cpp/PA4/Classes
scp Classes/*.h rikhardur19@skel.ru.is:~/cpp/PA4/Classes
scp Helpers/*.cpp rikhardur19@skel.ru.is:~/cpp/PA4/Helpers
scp Helpers/*.h rikhardur19@skel.ru.is:~/cpp/PA4/Helpers
scp Models/*.cpp rikhardur19@skel.ru.is:~/cpp/PA4/Models
scp Models/*.h rikhardur19@skel.ru.is:~/cpp/PA4/Models
scp Templates/*.cpp rikhardur19@skel.ru.is:~/cpp/PA4/Templates
scp Templates/*.h rikhardur19@skel.ru.is:~/cpp/PA4/Templates
scp Resources/*.txt rikhardur19@skel.ru.is:~/cpp/PA4/Resources
scp Saves/*.txt rikhardur19@skel.ru.is:~/cpp/PA4/Saves
scp Saves/backups/*.txt rikhardur19@skel.ru.is:~/cpp/PA4/Saves/backups